"""adds tokens column automatically

Revision ID: 01d31b12eac8
Revises: 
Create Date: 2021-09-06 17:27:56.092198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d31b12eac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('tokens', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'job_listings', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_listings', type_='unique')
    op.drop_column('job_listings', 'tokens')
    # ### end Alembic commands ###
